"""Import side effects register the built-in catalog."""

from . import adversarial_loop as adversarial_loop  # noqa: F401
from . import always_host_error as always_host_error  # noqa: F401
from . import always_partial as always_partial  # noqa: F401
from . import ask_user_only as ask_user_only  # noqa: F401
from . import ast_transform as ast_transform  # noqa: F401
from . import attack_generator as attack_generator  # noqa: F401
from . import budget_hog as budget_hog  # noqa: F401
from . import calibration as calibration  # noqa: F401
from . import cascade as cascade  # noqa: F401
from . import catalog_self_test as catalog_self_test  # noqa: F401
from . import chain_with_adapter as chain_with_adapter  # noqa: F401
from . import clarify_then_delegate as clarify_then_delegate  # noqa: F401
from . import classifier as classifier  # noqa: F401
from . import cond_dispatch as cond_dispatch  # noqa: F401
from . import constant as constant  # noqa: F401
from . import content_hash_memo as content_hash_memo  # noqa: F401
from . import convention_adapter as convention_adapter  # noqa: F401
from . import conversation as conversation  # noqa: F401
from . import dedup_then_map as dedup_then_map  # noqa: F401
from . import diff_writer as diff_writer  # noqa: F401
from . import directory_input as directory_input  # noqa: F401
from . import directory_writer as directory_writer  # noqa: F401
from . import dynamic_dispatch as dynamic_dispatch  # noqa: F401
from . import echo as echo  # noqa: F401
from . import ensemble as ensemble  # noqa: F401
from . import failure_classifier as failure_classifier  # noqa: F401
from . import function_map_editor as function_map_editor  # noqa: F401
from . import function_map_writer as function_map_writer  # noqa: F401
from . import infinite_descent as infinite_descent  # noqa: F401
from . import inherit_chain as inherit_chain  # noqa: F401
from . import judge as judge  # noqa: F401
from . import kind_chooser as kind_chooser  # noqa: F401
from . import kind_lister as kind_lister  # noqa: F401
from . import map_reduce as map_reduce  # noqa: F401
from . import meta_planner as meta_planner  # noqa: F401
from . import monty_exec as monty_exec  # noqa: F401
from . import noop_fail as noop_fail  # noqa: F401
from . import noop_fail_monty as noop_fail_monty  # noqa: F401
from . import pairwise_preference as pairwise_preference  # noqa: F401
from . import patch_applier_proxy as patch_applier_proxy  # noqa: F401
from . import patch_set_writer as patch_set_writer  # noqa: F401
from . import pipeline as pipeline  # noqa: F401
from . import precondition_gate as precondition_gate  # noqa: F401
from . import program_writer as program_writer  # noqa: F401
from . import py_spin as py_spin  # noqa: F401
from . import prose_writer as prose_writer  # noqa: F401
from . import provider_swap as provider_swap  # noqa: F401
from . import random_pick as random_pick  # noqa: F401
from . import refine_until as refine_until  # noqa: F401
from . import regression_canary as regression_canary  # noqa: F401
from . import repo_walker as repo_walker  # noqa: F401
from . import retry_wrapper as retry_wrapper  # noqa: F401
from . import rlm_loop as rlm_loop  # noqa: F401
from . import rubric_grader as rubric_grader  # noqa: F401
from . import schema_designer as schema_designer  # noqa: F401
from . import score_aggregator as score_aggregator  # noqa: F401
from . import subset_pick as subset_pick  # noqa: F401
from . import tournament as tournament  # noqa: F401
from . import transformer as transformer  # noqa: F401
