"""Minimal inputs for catalog_self_test and contract invariants."""

from __future__ import annotations

from typing import Any

from ._shared import content_hash


def minimal_input(name: str) -> Any:
    return {
        "constant": {"value": None},
        "ask_user_only": {"question": "?"},
        "monty_exec": {"code": "input"},
        "prose_writer": {"task": "test", "context": None},
        "classifier": {"text": "a", "labels": ["a"]},
        "judge": {"candidate": "x", "criteria": "ok"},
        "program_writer": {"task": "return ok", "context": None, "output_schema": {}},
        "map_reduce": {"items": [], "map_kind": "echo", "reduce_kind": None},
        "retry_wrapper": {"inner_input": {"value": 1}, "inner_kind": "constant", "max_attempts": 1},
        "ensemble": {"inner_input": {"value": 1}, "inner_kind": "constant", "n": 0, "aggregator_prompt": ""},
        "clarify_then_delegate": {"task": "x", "child_kind": "echo"},
        "random_pick": {"inner_input": {}},
        "subset_pick": {"inner_input": {"value": 1}, "subset": ["constant"]},
        "inherit_chain": {"task": "x", "depth": 0},
        "always_host_error": {"code": "executor_error"},
        "budget_hog": {"target": "steps"},
        "provider_swap": {"inner_input": {"value": 1}, "inner_kind": "constant"},
        "dynamic_dispatch": {"chooser": "literal", "literal_kind": "constant", "inner_input": {"value": 1}},
        "cond_dispatch": {"branches": [], "default_kind": "constant", "inner_input": {"value": 1}},
        "cascade": {"inner_input": {"value": 1}, "kinds": ["constant"], "stop_predicate": "True"},
        "score_aggregator": {"scores": [], "policy": "weighted_mean"},
        "content_hash_memo": {"inner_kind": "constant", "inner_input": {"value": 1}, "memo": {}},
        "dedup_then_map": {"items": [], "inner_kind": "echo"},
        "schema_designer": {"domain": "test", "examples": []},
        "diff_writer": {"file": "a.txt", "content": "", "change": "none"},
        "patch_set_writer": {"files": {}, "task": "none"},
        "directory_writer": {"task": "empty tree", "shape": "tree"},
        "conversation": {"system": "s", "turns": []},
        "kind_chooser": {"task": "return input"},
        "rubric_grader": {"candidate": "x", "rubric": []},
        "pairwise_preference": {"a": 1, "b": 2, "criterion": "best"},
        "attack_generator": {"target_kind": "echo", "target_input_template": {}, "attack_goal": "none"},
        "failure_classifier": {"step_result": {"outcome": "ok", "value": 1, "host_error": None}},
        "convention_adapter": {"source_kind": "echo", "target_kind": "echo", "source_value": {"value": 1}},
        "function_map_writer": {"signatures": {}, "context": None},
        "function_map_editor": {"current": {}, "edits": []},
        "ast_transform": {"ast": {}, "transform": "none"},
        "directory_input": {"tree": {}, "task": "return empty"},
        "repo_walker": {"tree": {}, "per_file_kind": "echo", "predicate": "True"},
        "patch_applier_proxy": {"patches": []},
        "pipeline": {"stages": [], "initial": None},
        "precondition_gate": {"predicate": "False", "inner_kind": "echo", "inner_input": {}},
        "transformer": {"inner_input_template": {"value": 1}, "inner_kind": "constant"},
        "meta_planner": {"task": "do nothing"},
        "refine_until": {"inner_input": {"value": "ok"}, "inner_kind": "constant", "judge_kind": "judge", "max_rounds": 0},
        "tournament": {"candidates": [], "judge_kind": "pairwise_preference"},
        "calibration": {"grader_kind": "rubric_grader", "examples": []},
        "adversarial_loop": {"target_kind": "echo", "seed_input": {}, "max_rounds": 0, "success_predicate": "none"},
        "regression_canary": {"frozen_kind": "constant", "frozen_input": {"value": 1}, "expected_value_hash": content_hash(1)},
        "chain_with_adapter": {"first_kind": "constant", "first_input": {"value": {"value": 1}}, "second_kind": "constant"},
        "kind_lister": {},
        "always_partial": {},
        "rlm_loop": {"task": "return ok", "max_iterations": 1},
    }.get(name, {})
